// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCBlpbdJW_CO3UV3wWyvdbQjO7VipiEwU',
    appId: '1:330744186242:web:57ee5522b581ee59b8fb9b',
    messagingSenderId: '330744186242',
    projectId: 'uol-ems',
    authDomain: 'uol-ems.firebaseapp.com',
    storageBucket: 'uol-ems.firebasestorage.app',
    measurementId: 'G-ZJZRDCKDWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-HtPvs-rY4wbaD8tsvfc2Lr2L3k2ZLdw',
    appId: '1:330744186242:android:f1dfed068b8d610fb8fb9b',
    messagingSenderId: '330744186242',
    projectId: 'uol-ems',
    storageBucket: 'uol-ems.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5Ypw4FGWblo-kbbZm0pet94kn1FPWuc',
    appId: '1:330744186242:ios:645a78c35e178b35b8fb9b',
    messagingSenderId: '330744186242',
    projectId: 'uol-ems',
    storageBucket: 'uol-ems.firebasestorage.app',
    androidClientId: '330744186242-p1503sto72jalvm02ch203irtjj9bbf7.apps.googleusercontent.com',
    iosClientId: '330744186242-b2emb45m0sacuesrv8rtf4hmia0b7llk.apps.googleusercontent.com',
    iosBundleId: 'com.example.uolEms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI5Ypw4FGWblo-kbbZm0pet94kn1FPWuc',
    appId: '1:330744186242:ios:645a78c35e178b35b8fb9b',
    messagingSenderId: '330744186242',
    projectId: 'uol-ems',
    storageBucket: 'uol-ems.firebasestorage.app',
    androidClientId: '330744186242-p1503sto72jalvm02ch203irtjj9bbf7.apps.googleusercontent.com',
    iosClientId: '330744186242-b2emb45m0sacuesrv8rtf4hmia0b7llk.apps.googleusercontent.com',
    iosBundleId: 'com.example.uolEms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCBlpbdJW_CO3UV3wWyvdbQjO7VipiEwU',
    appId: '1:330744186242:web:6bad2db6074b212bb8fb9b',
    messagingSenderId: '330744186242',
    projectId: 'uol-ems',
    authDomain: 'uol-ems.firebaseapp.com',
    storageBucket: 'uol-ems.firebasestorage.app',
    measurementId: 'G-91SRN23XC5',
  );

}